services:
  recipes-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    environment:
      - API_URL=http://recipes-gateway:8080
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    command: npm start -- --host 0.0.0.0 --poll 1000
    restart: always
  recipes-gateway:
    build: ./gateway
    environment:
      - RECIPES_URL=http://recipes-recipes:8080
      - RECIPE_TYPES_URL=http://recipes-recipe-types:8080
      - GATEWAY_HOST=http://recipes-gateway:8080
  recipes-recipes:
    build: ./recipes
    environment:
      - RECIPE_TYPES_URL=http://recipes-recipe-types:8080
  recipes-recipe-types:
    build: ./recipeTypes
    environment:
      - RECIPES_URL=http://recipes-recipes:8080
    depends_on:
      - recipes-recipes
    healthcheck:
      test: ["CMD", "curl", "-f", "http://recipes-recipes:8080/recipes"]
      interval: 10s
      retries: 5

volumes:
  frontend: {}