###
PUT localhost:8080/recipeTypes/7351b59e-08f3-4e5d-a703-22bd5c4affd1
Content-Type: application/json

{
  "name": "Breakfast"
}

###
PUT localhost:8080/recipeTypes/3d86dd98-5859-4250-a5c6-a6e830f3094e
Content-Type: application/json

{
"name": "Dinner"
}

### Add a recipe
PUT localhost:8080/recipes
Content-Type: application/json

{
  "name": "Chicken Karahi",
  "calories": 1000,
  "type": "3d86dd98-5859-4250-a5c6-a6e830f3094e"
}

### Add a recipe
PUT localhost:8080/recipes
Content-Type: application/json

{
  "name": "Pumpkin Chili",
  "calories": 850,
  "type": "3d86dd98-5859-4250-a5c6-a6e830f3094e"
}

### Add a recipe
PUT localhost:8080/recipes
Content-Type: application/json

{
  "name": "Hard Boiled Eggs",
  "calories": 250,
  "type": "7351b59e-08f3-4e5d-a703-22bd5c4affd1"
}

### Add a recipe
PUT localhost:8080/recipes
Content-Type: application/json

{
  "name": "Oatmeal",
  "calories": 200,
  "type": "7351b59e-08f3-4e5d-a703-22bd5c4affd1"
}
